import os
import platform
import pyfiglet
import psutil
banner = pyfiglet.figlet_format("osinfo", font="5lineoblique")
print(banner)
print('\n')
system = platform.system()
print("\033[1;31;40m > System:",system)
architect = platform.architecture()
print("\033[1;31;40m > Architecture:",architect)
machine = platform.machine()
print("\033[1;31;40m > Machine:",machine)
node = platform.node()
print("\033[1;31;40m > Node:",node)
processr = platform.processor()
print("\033[1;36;40m > Processor:",processr)
boot = psutil.boot_time()
print("\033[1;36;40m > Boot Time:",boot)
cpp = psutil.cpu_percent(1)
print("\033[1;37;40m > CPU Percentage:",cpp)
cpc = psutil.cpu_count()
print("\033[1;37;40m > CPU Cores:",cpc)
cpf = psutil.cpu_freq()
print("\033[1;37;40m > CPU Frequency:",cpf)
asl = psutil.getloadavg()
print("\033[1;37;40m > Average System Load",asl)
battery = psutil.sensors_battery()
print("\033[1;32;40m > Battery Info:",battery)
pid = os.getpid()
print("\033[1;33;40m > Process ID:",pid)
cwd = os.getcwd()
print("\033[1;33;40m > Current Working Directory:",cwd)
